
# Arterial health and brain development {#sec-chapter7}

Adapted from:

::: {.manuscript-title}
**Associations of arterial thickness, stiffness and blood pressure with brain morphology in early adolescence: A prospective population-based study**
:::

::: {.manuscript-authors} 
Defina, S., Silva, C.C.V., Cecil, C.A.M., Tiemeier, H., Felix, J.F., Mutzel, R.L., & Jaddoe, V.W.V. (2023). *Hypertension* [DOI](https://doi.org/10.1161/HYPERTENSIONAHA.123.21672)
:::

## Abstract {.unnumbered}
 [Background]{.underline}: Arterial wall thickness and stiffness, and high blood pressure have been repeatedly associated with poorer brain health. However, previous studies largely focused on mid- or late-life stages. It is unknown whether any arterial health–related brain changes may be observable already in adolescence.

 [Methods]{.underline}: We examined whether *(1)* carotid intima-media thickness, *(2)* carotid distensibility, and *(3)* systolic blood pressure and diastolic blood pressure, measured at the age of 10 years, were associated with brain volumes and white matter microstructure (ie, fractional anisotropy and mean diffusivity) at the age of 14 years. In addition to cross-sectional analyses, we explored associations with longitudinal change in each brain outcome from 10 to 14 years. Analyses were based on 5341 children from the Generation R Study.

 [Results]{.underline}: Higher diastolic blood pressure was associated with lower total brain volume (β [95% CI] = −0.04 [−0.07; −0.01]) and gray matter volume (β [95% CI] = −0.04 [−0.07; −0.01]) at the age of 14 years, with stronger associations in higher diastolic blood pressure ranges. Similar associations emerged between systolic blood pressure and brain volumes, but these were no longer significant after adjusting for birth weight. No associations were observed between blood pressure and white matter microstructure or between carotid intima-media thickness or distensibility and brain morphology.

 [Conclusions]{.underline}: Arterial blood pressure, but not intima-media thickness and distensibility, is associated with structural neuroimaging markers in early adolescence. Volumetric measures may be more sensitive to these early arterial health differences compared to microstructural properties of the white matter, but further studies are needed to confirm these results and assess potential causal mechanisms.

\newpage

## Links {.unnumbered}

::: {.content-visible when-format="html"}
* [Supplementary materials]({{< var supp7_general >}})
* [Project's code]({{< var chap7_repo >}})
* [OSF Pre-registration]({{< var chap7_prereg >}})
:::

## Introduction

## Methods

## Discussion

## References {.unnumbered}