project:
  type: book
  output-dir: docs

book:
  title: "Under the skin"
  subtitle: "Early-life stress exposure and the co-occurrence of mental and physical health problems"
  # author: "Serena Defina"
  cover-image: cover.png  
  # date: "3/25/2025"
  chapters:
    - index.qmd
    - 0.Introduction/introduction.qmd
    - part: "PART 1: The role of ELS in the development of mental and physical health"
      chapters:
      - 1.Chapter/ELS-comorbidity.qmd
      - 2.Chapter/ELS-lifestyle-moderators.qmd
      - 3.Chapter/ELS-brain.qmd
      - 4.Chapter/ELS-heart.qmd
    - part: "PART 2: Reciprocal relationships between mental and physical health problems"
      chapters:
      - 5.Chapter/longitudinal-codevelopment.qmd
    - discussion.qmd
  
  sidebar:
    title: "Under the skin<br><span style='color: #677281; font-weight: 500'>Early-life stress exposure and the co-occurrence of mental and physical health problems</span><br>"
    style: docked
    background: '#f0ebe2'
  search: true
  page-navigation: true
  repo-url: https://github.com/SereDef/PhD-thesis
  repo-actions: [source, issue]
  downloads: [pdf]

  page-footer: 
    left: "Serena Defina, 2025" 
    right: 
      - icon: github
        href: https://github.com/SereDef

# Only number sections 2 levels below the chapter level
number-depth: 3

# Bibliography
csl: apa.csl
bibliography: references.bib

# Outputs
format:
  html:
    theme: [cosmo, style_web.scss]
    grid:
      sidebar-width: 600px
  pdf:
    documentclass: scrreprt
    # fontfamily: arial
    # Display refecerences after every chapter
    # needs pandoc version >= 2.11 to work
    # filters:
    #  - ./_extensions/pandoc-ext/section-bibliographies/section-bibliographies.lua
    # Add index
    # include-in-header: 
    #   text: |
    #     \usepackage{makeidx}
    #     \makeindex
    # include-after-body: 
    #   text: |
    #     \printindex
  docx:
    reference-doc: style_doc.docx



