project:
  type: book
  output-dir: docs # for GitHub pages deployment

book:
  title: "under the skin"
  subtitle: "Early-life stress exposure and the co-occurrence of mental and physical health problems"
  author: "Serena Defina"
  cover-image: img/cover.png  
  chapters:
    - index.qmd
    - 0.preface.qmd
    - part: " "
      chapters:
      - 1.Introduction/introduction.qmd
    - part: "**PART 1**: The role of ELS in the development of mental and physical health"
      chapters:
      - 2.Chapter/ELS-comorbidity.qmd
      - 3.Chapter/ELS-lifestyle-moderators.qmd
      - 4.Chapter/ELS-brain.qmd
      - 5.Chapter/ELS-heart.qmd
    - part: "**PART 2**: Reciprocal relationships between mental and physical health problems"
      chapters:
      - 6.Chapter/longitudinal-codevelopment.qmd
      - 7.Chapter/arterial-brain.qmd
    - 8.Discussion/discussion.qmd
  
  sidebar:
    title: "under the skin<br><span style='color: #677281; font-weight: 500'>Early-life stress exposure and the co-occurrence of mental and physical health problems</span><br>"
    style: docked
    background: '#f0ebe2'
  search: true
  page-navigation: true
  repo-url: https://github.com/SereDef/PhD-thesis
  repo-actions: [source, issue]
  downloads: [pdf]

  page-footer: 
    left: "Author: Serena Defina, 2025. Built with sweat, tears and Quarto." 
    right: 
      - icon: github
        href: https://github.com/SereDef

# Only number sections 2 levels below the chapter level
number-depth: 2

# Bibliography
csl: apa.csl
bibliography: [references.bib, # TMP
               1.Introduction/introduction_bibliography.bib, 
               2.Chapter/ELS-comorbidity_bibliography.bib,
               3.Chapter/ELS-lifestyle-moderators_bibliography.bib,
               7.Chapter/arterial-brain_bibliography.bib,
               ]

# Outputs
format:

  html:
    theme: [cosmo, style_web.scss]
    grid:
      sidebar-width: 600px # Widen sidebar for longer chapter titles
    include-after-body: 
      text: <script type="application/javascript" src="/sidebar-tweak.js"></script> # Adjust sidebar chapter structure
    lightbox: true # click to see a larger version of the image
  
  pdf:
    documentclass: scrreport # srcbook
    keep-tex: true
    include-in-header: style_pdf.sty 
    include-before-body: thesis_info.tex
    fig-pos: "H"  # Non-floating figures
    filters:
      - quarto
      - section-bibliographies # Display references after every chapter
      - _extensions/quotify.lua # Quotes 
    reference-section-title: References
    citeproc: false # Disable citeproc to use biblatex
    

  docx:
    reference-doc: style_doc.docx
    filters:
      - quarto
      - section-bibliographies  # Display references after every chapter
    reference-section-title: References
    citeproc: true # false is recommended but does not work 




