
# Lifestyle factors, ELS and adolescent psycho-physical health {#sec-chapter3}

Adapted from:

::: {.manuscript-title}
**The role of lifestyle factors in the association between early-life stress and adolescent psycho-physical health: Moderation analysis in two European birth cohorts**
:::

::: {.manuscript-authors} 
**Defina, S.**, Woofenden, T., Baltramonaityte, V., Tiemeier, H., Fairchild, G., Felix, J. F., Cecil, C.A.M., & Walton, E. (2024). *Preventive Medicine*. [DOI](https://doi.org/10.1016/j.ypmed.2024.107926)
:::

## Abstract {.unnumbered}
 [Objective]{.underline}: Early-life stress (ELS) is an established risk factor for a host of adult mental and physical health problems, including both depression and obesity. Recent studies additionally showed that ELS was associated with an increased risk of comorbidity between mental and physical health problems, already in adolescence. Healthy lifestyle factors, including physical activity, sleep and diet have also been robustly linked to both emotional and physical wellbeing. However, it is yet unclear whether these lifestyle factors may moderate the association between ELS and psycho-physical comorbidity.

 [Methods]{.underline}: We investigated whether *(a)* participation in physical activity, *(b)* sleep duration, and *(c)* adherence to a Mediterranean diet, moderated the relationship between cumulative ELS exposure over the first 10 years of life and psycho-physical comorbidity at the age of 13.5 years. Analyses were conducted in 2022-2023, using data from two large adolescent samples based in the UK (ALSPAC; n=8428) and The Netherlands (Generation R; n=4268).

 [Results]{.underline}: Exposure to ELS was significantly associated with a higher risk of developing comorbidity, however this association was not modified by any of the three lifestyle factors investigated. Only physical activity was significantly associated with a reduced risk of comorbidity in one cohort (OR*$_{ALSPAC}$* [95%CI] = 0.73 [0.59; 0.89]).

 [Conclusions]{.underline}: In conclusion, while we found some evidence that more frequent physical activity may be associated with a reduction in psycho-physical comorbidity, we did not find evidence in support of the hypothesised moderation effects. However, more research is warranted to examine how these associations may evolve over time.

\newpage

## Links {.unnumbered}
* [Project's code]({{< var chap3_repo >}})

## Keywords {.unnumbered}
Adverse Childhood Experiences; Comorbidity; Physical Activity; Sleep; Diet, Mediterranean; Depression; Adiposity; moderation analysis.

## Abbreviations {.unnumbered}
Avon Longitudinal Study of Parents and Children (ALSPAC), Body Mass Index (BMI), Confidence Interval (CI), Child Behavior Checklist (CBCL), Dual-energy X-ray absorptiometry (DXA), Early Life Stress (ELS), Food Frequency Questionnaire (FFQ), Generation R (GenR), Odds Ratio (OR), Strengths and Difficulties Questionnaire (SDQ), Variance Inflation Factor (VIF), United Kingdom (UK).

\newpage

## Introduction

In summary, this book has no content whatsoever [@Fraser2013; @Boyd2012]. But I shall write it anyway cause. Cause I kind of do have no choice so, checking justification works

## Methods

## Discussion

## References {.unnumbered}