# General Introduction {#sec-chapter1}

## Early-life stress (ELS)
When my mother was pregnant with me, my older brother died of a congenital condition. I never met the little guy, never experienced any grief myself. Yet, for the longest time I thought that, somehow, his death had cast a sort of shadow over the rest of my life. And I was not the only one. The idea that exposure to stressful experiences during *"critical" periods* of early development wields profound, long-term impact on emotional and physiological regulation, is nothing new. Sigmund Freud, among others, made quite a sensational career out of it, and - perhaps partly because of the success of psychoanalytic theories - the scientific literature on the topic today is almost intimidatingly vast.

So vast in fact, that it requires a pinch of terminology clarification, before we can dive into it. For the remainder of this book, I will use the term "Early-Life Stress" (ELS) to refer to a host of adverse life events or conditions, that are experienced during the first years of life, e.g., in childhood, and, even earlier, during gestation. These experiences (sometimes also referred to as “childhood trauma”, “maltreatment”, “early adversity”, or “adverse childhood experiences”) encompass a wide range of stressors, including neglect and abuse, bereavement, bullying but also poverty, material deprivation and/or parental psychopathology [@Heim2020].

ELS is a widely studied concept, partly because it is surprisingly common: more than half the population experiences at least one form of ELS before the age of 18 years [@Madigan2024]. But more importantly, ELS is one of strongest, most consistent predictors of mental health problems later in life, particularly depression [@Li2016; @LeMoult2020; @Li2023].

Systematic scientific investigations into ELS and its consequences, really gained momentum in the late 90s, when large-scale epidemiological studies, began to also highlight a relationship between ELS and an increased risk of chronic diseases and premature mortality (e.g. [@Felitti1998]). This line of evidence also proved very robust over time, so ELS is now a well-recognised risk factor for cardio-metabolic health problems, including obesity [@Wiss2020; @Danese2014], type 2 diabetes [@Zhu2022], hypertension and cardio-vascular disease [@Jakubowski2018; @Jacquet-Smailovic2022].

## Mental & physical health: a comorbidity paradigm

Interestingly, parallel to this growing interest in the effects of stress and psychosocial factors on physical health, the early 2000s also witnessed a surge of epidemiological studies uncovering the relationship between depression and cardio-metabolic health problems[@Penninx2001; @VanderKooy2007; @Luppino2010]. Historically, these two conditions had been largely investigated as separate entities, each with distinct risk factors and treatment approaches. Their connection was not entirely overlooked (see for example early theoretical work by @Engel1977), but it remained peripheral to mainstream medical research until relatively recently.

As more evidence accumulated that depression and cardio-metabolic conditions tend to co-occur [@Anwar2018; @Blasco2020; @Gutiérrez-Rojas2020], several potential mechanisms have been proposed to explain this observed comorbidity [@Milaneschi2019]. One possibility is that these conditions share common risk factors, such as genetic liability for instance, but also ELS exposure, as discussed above and supported by a recent large scale meta-analysis [@Souama2023]. It is also possible that experiencing depression may directly increase the risk of developing cardio-metabolic health problems later in life. For example, in two meta-analyses based on longitudinal data, depression was found to be risk factor for obesity and diabetes [@Mannan2016; @Ditmars2022]. Other longitudinal meta-analyses however, have also shown, in turn, that poor cardio-metabolic health was a robust predictor of later depression [@Zhou2024], supporting the hypothesis of a bi-directional relationship.

## ELS and psycho-physical health: towards an integrated approach

So far, we have described a triangle of relationships - i.e., between *a)* ELS and mental health, *b)* ELS and cardio-metabolic health, and *c)* mental and cardio-metabolic health (@fig-thesis-summary A), which received considerable attention in the medical literature. This isn't surprising. Depression and cardio-metabolic conditions are among the leading causes of death and disability worldwide, shaping an enormous public health burden which is largely preventable [@Anwar2018]. ELS is a promising shared risk factor, which can be measured years - and even decades - before clinical symptoms emerge, making it an ideal candidate for informing early detection and improving the integrated prevention of psycho-physical health problems.

::: {.content-visible when-format="html"}
![**Schematic representation of this thesis, in the context of previous literature**<br>(A) A schematic summary of the existing evidence, on the relationships under study. This is largely based on adult outcomes and retrospectively measured ELS exposure (indicated by the dashed line).<br>(B) A Schematic summary of the relationships examined in this thesis.](F1_thesissumm.png){width=100% #fig-thesis-summary}
:::

::: {.content-visible unless-format="html"}
![**Schematic representation of this thesis, in the context of previous literature**\newline(A) A schematic summary of the existing evidence, on the relationships under study. This is largely based on adult outcomes and retrospectively measured ELS exposure (indicated by the dashed line).\newline(B) A Schematic summary of the relationships examined in this thesis.](F1_thesissumm.pdf){width=100% #fig-thesis-summary}
:::

However, there are three key challenges that need to be addressed, before these findings could be effectively translated into clinical practice. 

Firstly, as briefly noted above, the literature is very heterogenous in its definition of ELS, with many studies focusing on specific types of adversity (e.g., childhood neglect and abuse). However, there is convincing evidence that exposure to multiple stressors - i.e., different sources of stress, as well as repeated or continued exposure over time - has much worse consequences for psycho-physical health, compared to individual stressors [@Evans2013; @Hughes2017]. This underscores the importance of identifying of children who face multiple forms of ELS, as they may represent a particularly vulnerable population, who should be prioritized in intervention programs.

Secondly, existing studies typically only address one "side" of this triad of relationships. For instance, while ELS has been linked to both depression and obesity independently, its role in determining their co-occurrence remains heavily understudied. Consequently, it is hard to establish the relative importance of ELS as a risk factor for each disorder in isolation vs. their comorbidity, which poses an obstacle to the development of integrated prevention and intervention [@Anwar2018]. 

Lastly, the overwhelming majority of studies investigating either the role of ELS, or the(bidirectional) relationships between mental and physical health, has been conducted in adult or aging populations. 

On one hand, this brings about important measurement issues. Namely, the proposed relationship between ELS and adult psycho-physical health relies heavily on retrospective reports of ELS exposure, which may have introduced recall bias, unrealistically inflating the association estimates reported by the literature [@Reuben2016].

On the other hand, both depression and cardio-metabolic health problems very often find their onset well before adulthood. A growing number of adolescents, for instance, experience depressive symptoms before the age of 20 years [@Keeley2021; @Patalay2019]. Concurrently, while cardio-metabolic endpoints such as myocardial infarction and diabetes are traditionally associated with later life stages, their prodromal forms, including hypertension, dyslipidemia, and obesity, manifest more and more frequently between childhood and adolescence [@WHO2022; @NCD-RisC2017]. Intervening during this early developmental window could be crucial to mitigate the progression of such prodromal psycho-physical symptoms into chronic mental and physical health conditions later in life.

In this context, prospective cohort studies that begin at conception and capture a broader spectrum of ELS exposures and psycho-physical symptoms, are essential to map causal pathways and inform on optimal intervention windows.

## This thesis: one step back in time

This thesis (@fig-thesis-summary B) aims to address some of these limitations and open questions. 

**Part 1** will focus on characterizing the prospective relationship between ELS and adolescent psycho-physical health. First, in @sec-chapter2, I quantify the relationship between ELS exposure during two key developmental periods (i.e. pregnancy and childhood) and adolescent *a)* internalizing symptoms, *b)* adiposity, and *c)* their comorbidity. @sec-chapter3 further explores wether three common lifestyle factors (i.e., physical activity, sleep duration, and diet quality) may moderate the associations identified in @sec-chapter2. I will then take a closer look at the potential "biological scars" that pre- and postnatal ELS exposure may leave behind on children's brains (@sec-chapter4) and on their hearts (@sec-chapter5). 

In **Part 2** I will then characterize the reciprocal relationship between mental and cardio-metabolic health across childhood and adolescence. @sec-chapter6 examines the longitudinal co-development of depressive symptoms and several markers of cardio-metabolic health from childhood to early adulthood. In @sec-chapter7, I assess the relationship between early cardio-vascular health markers (i.e., arterial health and blood pressure) and the developing brain. 

## This thesis: setting
To address the questions in each of the chapters of this thesis, we leveraged data from two longitudinal population-based birth cohorts: the Generation R Study and the Avon Longitudinal Study of Parents and Children (ALSPAC). These are among the world's largest resources for developmental science, both in terms of sample size and because of the breadth of measures that have been collected repeatedly over the first two decades of life (i.e. from fetal life to early adulthood).

### The Generation R Study
The Generation R Study is a population-based birth cohort based in Rotterdam (the Netherlands). The study enrolled 9,778 pregnant women who delivered their babies between April 2002 and January 2006 [@Kooijman2016; **NEW DESIGN PAPER**]. Mothers, fathers and children are in ongoing follow-up, which includes questionnaires, interviews, biological sampling and detailed study center visits at 3/4-year intervals [@Kooijman2016; **NEW DESIGN PAPER**]. Please note that further details about Generation R data are available through a fully searchable data dictionary app ([GuRu](https://seredef-guru.share.connect.posit.cloud/)) that was developed alongside this thesis. 

Generation R data was used in @sec-chapter2, @sec-chapter3, @sec-chapter4, @sec-chapter5, and @sec-chapter7. The response rate at the 14 years follow-up (when most of the outcomes in this thesis have been measured) was 64%. 

### The ALSPAC study
The ALSPAC study is a population-based birth cohort based in Avon (United Kingdom). The study enrolled 14,541 pregnant women with expected delivery dates between 1st April 1991 and 31st December 1992; 13,988 children were alive at 1 year of age. When children were approximately 7 years old, additional eligible cases were re-invited, resulting in a total sample of 15,447 pregnancies and 14,901 children who were alive at 1 year of age [@Boyd2012; @Fraser2013; @Northstone2019]. Study data were collected and managed using REDCap electronic data capture tools hosted at the University of Bristol [@Harris2009]. Please note that the [ALSPAC website](http://www.bristol.ac.uk/alspac/researchers/our-data/) contains details of all the data that is available through a fully searchable data dictionary and variable search tool. 

ALSPAC data was used in @sec-chapter2, @sec-chapter3, and @sec-chapter6. The response rate at the 14 years follow-up (when most of the outcomes in this thesis have been measured) was 61%.

## References {.unnumbered}
::: {.sectionrefs}
:::