
# ELS and adolescent psycho-physical health {#sec-chapter2}

Adapted from:

::: {.manuscript-title}
**Differential effects of pre- and postnatal early-life stress on internalizing, adiposity and their comorbidity**
:::

::: {.manuscript-authors}
**Defina, S.**, Woofenden, T., Baltramonaityte, V., Pariante, C. M., Lekadir, K., Jaddoe, V. W., Serdarevic, F., Tiemeier, H., Walton, E., Felix, J. F., & Cecil, C. A. M., *on behalf of the EarlyCause Consortium. (2023). _JAACAP_. [DOI](https://doi.org/10.1016/j.jaac.2023.05.034)
:::

## Abstract {.unnumbered}
 [Objective]{.underline}: Depression and obesity are two highly prevalent and often comorbid conditions. Exposure to early-life stress (ELS) has been associated with both depression and obesity in adulthood, as well as their preclinical manifestations during development. However, it remains unclear whether: *(i)* associations differ depending on the timing of stress exposure (prenatal vs postnatal) and *(ii)* ELS is a shared risk factor underlying the comorbidity between the two conditions.

 [Method]{.underline}: Leveraging data from two large population-based birth cohorts (ALSPAC: n=8428 (52% male participants); Generation R: n=4268 (48% male participants)), we constructed comprehensive cumulative measures of prenatal (in utero) and postnatal (from birth to 10 years) ELS. At age 13.5 years we assessed: a) internalizing symptoms (using maternal reports); b) fat mass percentage (using dual-energy X-ray absorptiometry); c) their comorbidity, defined as the co-occurrence of high internalizing and high adiposity.

 [Results]{.underline}: Both prenatal (*total effect* [95%CI] = 0.20 [0.16; 0.22]) and postnatal stress ($\beta$ [95%CI] = 0.22 [0.17; 0.25]) were associated with higher internalizing symptoms, with evidence of a more prominent role of postnatal stress. A weaker association (primarily driven by prenatal stress) was observed between stress and adiposity (prenatal: 0.07 [0.05; 0.09]; postnatal: 0.04 [0.01; 0.07]). Both pre- (OR [95%CI] = 1.70 [1.47; 1.97]) and postnatal stress (1.87 [1.61; 2.17]) were associated with an increased risk of developing comorbidity.

 [Conclusion]{.underline}: We found evidence of *(i)* timing and *(ii)* shared causal effects of ELS on psycho-cardiometabolic health in adolescence, but future research is warranted to clarify how these associations may unfold over time.

## Introduction

The co-occurrence of depression and obesity is a rising public health concern, affecting increasingly younger populations [@Sutaria2019]. Individuals with obesity are ~30-40% more likely to develop depression compared to the general population [@Pereira-Miranda2017]. In turn, depression also increases the risk of developing obesity [@Pratt2014] and related cardiometabolic disease [@Hare2014]. While the relationship between depression and adiposity is likely multifactorial and complex, the observed comorbidity between the two may be partially explained by shared environmental risk factors, such as exposure to stressful experiences early in life [@Shonkoff2012].

Indeed, early-life stress (ELS) is a well-established risk factor for both adult depression [@Li2016] and obesity [@Danese2014]. In children and adolescents, ELS exposure in utero and postnatally (e.g., adverse childhood experiences) have been separately linked to preclinical manifestations of depression, such as internalizing problems [@Cecil2017; @VandenBergh2020], and several adiposity measures [@Elsenburg2017; @Burgueño2020].

Identifying critical exposure windows (i.e., prenatal vs postnatal) can provide important insights into the best timing for prevention and intervention programs, and shed light on the mechanisms through which stress may lead to disease [@Hartman2018]. However, very few studies prospectively investigated the influence of both pre- and postnatal stress on these outcomes, and, because stress shows continuity over time, it is unclear whether *(a)* previously reported postnatal associations may partly reflect preceding prenatal exposures (i.e., prenatal ELS as confounder), and *(b)* observed prenatal associations may be partly mediated by postnatal ELS (i.e., postnatal ELS as mediator).

Further, existing studies have examined ELS associations with internalizing and adiposity either separately [@Slopen2014] or as part of a broader “multisystemic” disease constructs [@Juster2016]. It remains unknown whether ELS represents a shared risk factor for comorbid emotional problems and adiposity. Establishing such association is important, since protocols for the integrated detection and management of these health conditions are lacking [@Anwar2018], and differential patterns of ELS exposure may help identify subgroups of adolescents at higher risk for comorbidity.

To address these gaps, we leveraged longitudinal data from two population-based prospective birth cohorts to examine *(i)* how pre- and postnatal ELS (up to age 10 years) associate to internalizing symptoms and adiposity in early adolescence (i.e., at age 13 years), taking into account potential confounding and mediation effects; and *(ii)* whether ELS accounts for comorbidity between internalizing problems and excess adiposity, above its contribution to each health outcome individually. Based on previous findings, we expect that both pre- and postnatal ELS prospectively associate with internalizing symptoms and adiposity, as well as their comorbidity. No a priori hypotheses were specified regarding the relative importance of pre- vs postnatal ELS.

## Methods

This manuscript follows STROBE guidelines [@vonElm2008].

### Participants
Our sample was drawn from two population-based cohorts: the Generation R Study (GenR), including 9,778 pregnant women in Rotterdam (the Netherlands), who delivered their babies between April 2002 and January 2006 [@Kooijman2016]; and the Avon Longitudinal Study of Parents and Children (ALSPAC) involving 14,541 pregnant women in Avon (UK), with delivery dates between April 1991 and December 1992 [@Boyd2013; @Fraser2013]. The [ALSPAC website](http://www.bristol.ac.uk/alspac/researchers/our-data/) contains details of all the data that is available through a fully searchable data dictionary and variable search tool.

Response rates at the 13 years follow-up were 64% in GenR and 61% in ALSPAC. Participants with > 50% missing ELS variables in the pre- or postnatal period were excluded, as were all twins. In the case of non-twin siblings, only one was selected (see Figure S1, available online). The final sample included 4268 (GenR) and 8428 (ALSPAC) children.

#### Ethical standards
Ethical approval was obtained from the medical ethical committee of Erasmus MC, University Medical Center Rotterdam and from the ALSPAC Ethics and Law Committee and the Local Research Ethics Committees. Written informed consent was obtained for all participants and both studies conform with the World Medical Association Declaration of Helsinki (2013).

### Measures
#### Prenatal and postnatal ELS
The prenatal (i.e., maternal exposure during pregnancy) and postnatal (i.e. from birth to 10 years) cumulative ELS scores comprise information about five stress domains in line with previous literature [@Cecil2014; @Rijlaarsdam2016]: life events (e.g., death of a parent), contextual risk (e.g., financial difficulties), parental risk (e.g., parental psychopathology), interpersonal risk (e.g., family conflicts) and direct victimization (only postnatally, e.g. maltreatment or bullying).  Note that, consistent with other work using this measure [@Schuurmans2022], we use the term “postnatal” (in contrast to “prenatal”) to encompass stressors experienced across childhood (i.e., until the age of 10 years), rather than immediately following birth. A detailed description of the ELS scores is provided in online **Supplement 1** (see also the score's [GitHub repository](https://github.com/SereDef/cumulative-ELS-score) for further details and scripts). Briefly, ~100 stress items were selected from each cohort, dichotomized into no risk (=0) or risk (=1), and assigned to a domain based on expert knowledge (see @fig-1.1 for an overview of included items). Within each domain, dichotomized risks were summed and divided by the number of items in the domain. Finally, domain scores were summed within periods to obtain prenatal and postnatal stress scores.

::: {.content-visible when-format="html"}
![**Temporal structure of the prenatal and postnatal early-life stress (ELS) score**<br>The two graphs summarize the complex temporal structure of the prenatal (on the left) and postnatal (on the right) ELS scores. Time is depicted on the x-axis on the scale of weeks (gestation) for prenatal and years for postnatal items. For each question/item on the y-axis, a coloured dot represents the timepoint(s) at which the item was measured, and a grey shadow indicates the time period the question refers to (e.g., "since pregnancy" or "in the last year"). Red dots and labels refer to ALSPAC items and blue dots/labels refer to Generation R items. Items are grouped by domain, as indicated by the background color (yellow for life events, red for contextual risk, blue for parental risk, green for interpersonal risk and purple for direct victimization). The solid black vertical line indicates the beginning of the exposure period of interest, i.e., conception (or start of pregnancy) for prenatal items and birth for postnatal items. The dashed grey lines additionally provide temporal markers, i.e., trimesters in the prenatal period and a span of 1 year in the postnatal period.](F1_ELStime.png){width=100% #fig-1.1}
:::

::: {.content-visible unless-format="html"}
![**Temporal structure of the prenatal and postnatal early-life stress (ELS) score**The two graphs summarize the complex temporal structure of the prenatal (on the left) and postnatal (on the right) ELS scores. Time is depicted on the x-axis on the scale of weeks (gestation) for prenatal and years for postnatal items. For each question/item on the y-axis, a coloured dot represents the timepoint(s) at which the item was measured, and a grey shadow indicates the time period the question refers to (e.g., "since pregnancy" or "in the last year"). Red dots and labels refer to ALSPAC items and blue dots/labels refer to Generation R items. Items are grouped by domain, as indicated by the background color (yellow for life events, red for contextual risk, blue for parental risk, green for interpersonal risk and purple for direct victimization). The solid black vertical line indicates the beginning of the exposure period of interest, i.e., conception (or start of pregnancy) for prenatal items and birth for postnatal items. The dashed grey lines additionally provide temporal markers, i.e., trimesters in the prenatal period and a span of 1 year in the postnatal period.](F1_ELStime.pdf){width=100% #fig-1.1}
:::

#### Internalizing symptoms
Internalizing symptoms were measured at an average age of 13.5 years (range: 12.5-16.8 years) using the Child behavior checklist (CBCL 6-18) [@Achenbach1999] in GenR and the Strengths and difficulties questionnaire (SDQ) [@Goodman2000] in ALSPAC. Both instruments are well-validated parental reports of emotional and behavioral functioning referring to the past 6 months, and have been shown to be comparable [@Goodman1999]. The CBCL internalizing subscale consists of 32 items rated on a 3-point scale, e.g., *"my child feels worthless or inferior"*. The SDQ emotional problems subscale contains 5 items rated on a 3-point scale, e.g., *"often unhappy, down-hearted or tearful"*.

#### Adiposity (fat mass)
Body composition was measured using a dual-energy X-ray absorptiometry (DXA) scanner at an average age of 13.5 years (range: 12.5-16.6 years). Technical details of these measurements are provided elsewhere [@Boyd2013; @Voortman2016]. Fat mass percentage was calculated by dividing the total body fat mass (kg) by the weight (kg) and multiplying by 100. To explore the importance of body fat distribution, measurements of android fat mass were also extracted from DXA scans.

#### Comorbidity
To compute psycho-cardiometabolic comorbidity, internalizing symptoms and fat mass percentage were first dichotomized into high versus low-moderate, based on a cohort-specific 80th percentile cut-off value. The dichotomized values were then used to assign children to four groups: "healthy" (both outcomes <80th percentile); "high internalizing" (internalizing >80th & fat mass percentage ≤80th); "high adiposity" (internalizing ≤80th & fat mass percentage >80th); and "comorbid" (both outcomes >80th percentile). 
For additional information see @tbl-1.1 and online **Supplement 2**.

#### Covariates
During pregnancy, mothers reported on their smoking status, alcohol consumption, and pre-pregnancy body mass index (BMI). Information about child sex and date of birth was extracted from registries. Ethnic background (only available for GenR children) was determined by questionnaire-based assessment of the country of origin of participants’ parents. Following Statistics Netherlands' guidelines [@Alders2001], if one of the parents was born abroad, the child’s ethnicity was determined according to that parent. If both parents were born abroad, the child was classified according to the mother’s birthplace. Six large national groups were identified (i.e., Cape Verdean, Dutch, Dutch Antillean, Moroccan, Surinamese, and Turkish). Smaller national groups were aggregated into five additional categories: "Africa and Middle East", "Asia and Oceania", "Europe", "Latin America", and "North America" (**Figure S5**). See @tbl-1.1 and online **Supplement 3** for additional information on covariates measurement and distribution.

### Statistical analysis
Analyses were run separately in the two cohorts, using R version 4.0.3 [@R2021] All scripts are available on the project [GitHub repository](https://github.com/SereDef/association-ELS-PCM-project).
Missing values in the exposure, covariate and outcome variables were imputed by conditional multiple imputation [@vanBuuren2018] using 60 iterations and 30 imputed datasets (for a complete assessment of missing values and detailed imputation strategy see **Supplement 4** and **Table S1**, available online). Model parameters were fit in each imputed dataset and then pooled according to Rubin's rules. Pre- and postnatal stress, internalizing and adiposity were standardized using a z transformation. All statistical tests were two-sided and interpreted at a p-value significance threshold of 0.05. To account for multiple comparisons, false discovery rate (FDR) correction was applied.

#### Association of prenatal ELS with internalizing symptoms and adiposity
For each continuous outcome (i.e., internalizing and adiposity), we performed a causal mediation analysis featuring prenatal stress as the exposure and postnatal stress as mediator [@Wang2015]. The method is described in detail in online **Supplement 5**. In summary, the "total" effect of prenatal ELS on each outcome was decomposed into a direct (i.e., not due to postnatal ELS) and indirect pathway (i.e., acting through postnatal ELS), allowing us to quantify the direct and mediated contribution of prenatal stress.

#### Association of postnatal ELS with internalizing symptoms and adiposity
For each continuous outcome, four multiple linear regression models were run: 1) baseline (covariate only) model; 2) prenatal stress + covariates model; 3) postnatal stress + covariates model; and 4) prenatal + postnatal stress + covariates model. The baseline model served as reference for the computation of R~inc~^2; the prenatal model was used to ensure comparability of estimates between approaches.

#### Association of prenatal and postnatal ELS with comorbidity
For the combined comorbidity outcome, two multinomial logistic regression models were performed, using the "healthy" group as reference, and pre-/postnatal stress as independent predictors. The odds ratios (OR) and 95% confidence intervals (CI) of developing comorbidity were visually compared to those of developing high internalizing and high adiposity only, to determine whether pre-/postnatal stress influence comorbidity beyond either health problem alone.

#### Follow-up and sensitivity analyses
We examined effect modification by sex and by ethnic background - in GenR only, given its multi-ethnical composition [@Kooijman2016]. Additionally, to explore the relative contribution of different types of stress, three regression models (for internalizing, adiposity and comorbidity) were run including all 9 domain scores (4 prenatal and 5 postnatal) as independent predictors.

To assess the impact of the imputation procedure on our results, we ran the analyses in the subsample with complete outcome data (i.e., both internalizing and adiposity). Finally, we tested the stability of our results using android fat mass as an alternative measure of adiposity.

## Results 

### Sample descriptives
Sample characteristics were pooled across imputed datasets and summarized in @tbl-1.1. Briefly, the ALSPAC sample included 8428 (48% male) children, whose mothers were 30% highly educated (i.e., held a college or university degree). The GenR sample included 4268 (52% male) participants, 62% of which were "Dutch" and 14% had highly educated (i.e., "higher, phase 2") mothers. Pre- and postnatal ELS were moderately correlated (r = GenR: 0.56; ALSPAC: 0.48; see online Supplement 1), whereas the correlation between internalizing symptoms and adiposity was weak (r = GenR: 0.15; ALSPAC: 0.11).

:::{#tbl-1.1}
```{=html}
{{< include "Table1.html" >}}
```
My interesting caption.
:::

### Associations of prenatal ELS with internalizing symptoms and adiposity
Results of the mediation analysis linking prenatal stress to internalizing and adiposity were highly consistent across cohorts (see @fig-1.2 and online **Table S2**).

About ~60% of the total effect (TE) of prenatal stress on internalizing symptoms (TE [95%CI] = GenR: 0.27 [0.23;0.30]; ALSPAC: 0.16 [0.13;0.18]) was mediated through postnatal stress (GenR: 0.16 [0.14;0.19]; ALSPAC: 0.10 [0.08;0.11]).
The TE of prenatal stress on adiposity (GenR: 0.12 [0.09;0.15]; ALSPAC: 0.04 [0.03;0.06]) was smaller compared to internalizing and largely (~70%) operating via the direct pathway (GenR: 0.08 [0.04;0.12]; ALSPAC: 0.03 [0.01;0.05]).

::: {.content-visible when-format="html"}
![**Prenatal early-life stress (ELS) contribution (causal mediation analysis results)**<br>Note: The causal estimates for the total effect (TE), natural direct (NDE) and natural indirect effect (NIE) of prenatal stress on internalizing symptoms (A. Generation R and B. ALSPAC) and adiposity (C. Generation R and D. ALSPAC) are displayed in the grey boxes. The percentage of the total effect due to direct and indirect pathway is reported between brackets and the respective p-values are marked in grey. The predominant path is highlighted with a thicker arrow. NDE = natural direct effect; NIE = natural indirect effect; TE = total effect.](F2_CMAres.png){width=100% #fig-1.2}
:::

::: {.content-visible unless-format="html"}
![**Prenatal early-life stress (ELS) contribution (causal mediation analysis results)**<br>Note: The causal estimates for the total effect (TE), natural direct (NDE) and natural indirect effect (NIE) of prenatal stress on internalizing symptoms (A. Generation R and B. ALSPAC) and adiposity (C. Generation R and D. ALSPAC) are displayed in the grey boxes. The percentage of the total effect due to direct and indirect pathway is reported between brackets and the respective p-values are marked in grey. The predominant path is highlighted with a thicker arrow. NDE = natural direct effect; NIE = natural indirect effect; TE = total effect.](F2_CMAres.pdf){width=100% #fig-1.2}
:::

### Association of postnatal ELS with internalizing symptoms and adiposity
Results of the hierarchical regressions examining the association of postnatal stress with internalizing and adiposity were also largely similar across cohorts (see @fig-1.3; online **Tables S3 and S4**).

Higher postnatal stress associated with increased internalizing symptoms both before ($\beta$ [95%CI] = GenR: 0.33 [0.29;0.37]; ALSPAC: 0.22 [0.19;0.25]) and after adjustment for prenatal stress (GenR: 0.27 [0.22;0.31]; ALSPAC: 0.19 [0.15;0.22]).

Higher postnatal stress also associated with increased adiposity (GenR: 0.10 [0.07;0.13]; ALSPAC: 0.03 [0.01;0.05]). The association remained after prenatal stress adjustment in GenR (0.07 [0.03;0.11]), but not in ALSPAC (0.02 [0.00;0.05]).

::: {.content-visible when-format="html"}
![**Postnatal early-life stress (ELS) contribution (hierarchical regression results)**<br>Note: In each cohort (A. Generation R and B. ALSPAC), the standardized beta estimates of pre- and postnatal ELS (and their 95% confidence intervals) are represented along the x-axis, using different color sets for internalizing symptoms (light and dark blue) and adiposity (yellow and orange). Estimates generated by the prenatal only model are presented on the first row and marked in lighter colours (i.e., light blue and yellow); these correspond to the TE displayed in Figure 2. Postnatal ELS beta estimates, before (round marker) and after (square marker) prenatal adjustment, are displayed in darker colors (blue and orange). For each model, the total and incremental R2 is reported in the legend below the graphs. The first number provides an indication of total model fit; the latter quantifies the increase in variance explained due to the introduction of the predictor (compared to the covariate only model).](F3_regress.png){width=100% #fig-1.3}
:::

::: {.content-visible unless-format="html"}
![**Postnatal early-life stress (ELS) contribution (hierarchical regression results)**<br>Note: In each cohort (A. Generation R and B. ALSPAC), the standardized beta estimates of pre- and postnatal ELS (and their 95% confidence intervals) are represented along the x-axis, using different color sets for internalizing symptoms (light and dark blue) and adiposity (yellow and orange). Estimates generated by the prenatal only model are presented on the first row and marked in lighter colours (i.e., light blue and yellow); these correspond to the TE displayed in Figure 2. Postnatal ELS beta estimates, before (round marker) and after (square marker) prenatal adjustment, are displayed in darker colors (blue and orange). For each model, the total and incremental R2 is reported in the legend below the graphs. The first number provides an indication of total model fit; the latter quantifies the increase in variance explained due to the introduction of the predictor (compared to the covariate only model).](F3_regress.pdf){width=100% #fig-1.3}
:::

### Association of prenatal and postnatal ELS with comorbidity
Higher stress in the prenatal (OR [95%CI] = GenR: 2.13 [1.84;2.47]; ALSPAC: 1.48 [1.28;1.71]) and postnatal periods (GenR: 2.37 [2.05;2.75]; ALSPAC: 1.61 [1.39;1.87]) was associated with higher odds of belonging to the comorbidity group compared to the healthy group (see @fig-1.4 and online **Table S5**). This association was the strongest compared to all other (single-outcome) groups. However, the CIs of the comorbidity estimates did overlap with those of high internalizing only (@fig-1.4 C and D).

::: {.content-visible when-format="html"}
![**Pre- and postnatal early-life stress (ELS) and psycho-cardiometabolic comorbidity**<br>(A, B) Scatterplots of internalizing symptoms (on the x axis) and fat mass percentage (on the y-axis), for the Generation R (A) and ALSPAC (B) cohorts. The univariate distributions of both primary outcomes are shown on the respective axes, with darker shadow indicating the 80th percentile cut-off used in construction of the comorbidity variable. Colour indicates the assigned group (green = healthy; blue = high internalizing; yellow = high adiposity; red = comorbid). Group sizes (i.e., n and percent of the total cohort sample) were pooled across imputed datasets and reported on the right of each scatterplot.<br>(C, D) Effect estimates for pre- and postnatal stress (and their 95%CIs) on the odds ratio (OR) scale are represented along the x-axis, with different colours depending on the comparison they refer to (yellow = healthy vs. high adiposity; blue = healthy vs. high internalizing; red = healthy vs. comorbid), in Generation R (C) and ALSPAC (D) children.](F4_comorb.png){width=100% #fig-1.4}
:::

::: {.content-visible unless-format="html"}
![**Pre- and postnatal early-life stress (ELS) and psycho-cardiometabolic comorbidity**<br>(A, B) Scatterplots of internalizing symptoms (on the x axis) and fat mass percentage (on the y-axis), for the Generation R (A) and ALSPAC (B) cohorts. The univariate distributions of both primary outcomes are shown on the respective axes, with darker shadow indicating the 80th percentile cut-off used in construction of the comorbidity variable. Colour indicates the assigned group (green = healthy; blue = high internalizing; yellow = high adiposity; red = comorbid). Group sizes (i.e., n and percent of the total cohort sample) were pooled across imputed datasets and reported on the right of each scatterplot.<br>(C, D) Effect estimates for pre- and postnatal stress (and their 95%CIs) on the odds ratio (OR) scale are represented along the x-axis, with different colours depending on the comparison they refer to (yellow = healthy vs. high adiposity; blue = healthy vs. high internalizing; red = healthy vs. comorbid), in Generation R (C) and ALSPAC (D) children.](F4_comorb.pdf){width=100% #fig-1.4}
:::

### Follow-up analyses
#### Interaction with sex and ethnic background
After stratifying by sex, in GenR, the association between prenatal ELS and adiposity was larger in girls than in boys (*Z*=1.89, *p*=.029), whereas that of postnatal ELS was slightly larger in boys (*Z*=-1.38, *p*=.083). A similar pattern of associations was found in ALSPAC but with smaller magnitudes (see **Figures S2-S4** and **Tables S6-S9**, available online). 

In GenR, Cape Verdian and Dutch Antillean children experienced the highest cumulative prenatal and postnatal stress followed by Turkish, Surinamese and Moroccan children (**Figure S5-B**). We did not find evidence for a significant interaction between pre- or postnatal ELS and the examined ethnic background groups on any outcome of interest (i.e., internalizing symptoms, adiposity or comorbidity; see **Table S10** and **Figure S5-C**, available online). Note however that the association between pre-/postnatal ELS and comorbidity in the "North American" group could not be estimated due to insufficient number of observations (i.e., comorbidity group size ≤ 5).

#### Contribution of specific stress domains
Across cohorts, internalizing symptoms were consistently associated with higher prenatal and postnatal parental risk (e.g., parental psychopathology), postnatal life events and direct victimization (see **Figure S6** and **Table S11**, available online). We found no consistent associations for adiposity. Only postnatal parental risk was consistently associated comorbidity status (vs. healthy) across cohorts (see **Figure S7** and **Table S12**, available online).

#### Sensitivity analyses
Restricting the analyses to participants with complete outcome data (n = GenR: 2749; ALSPAC: 4096) did not substantively change the reported findings (see **Figure S8** and **Tables S13-S15**, available online), nor did the use of android fat mass rather than fat mass percentage as a proxy of adiposity (see **Figure S9** and **Table S16**, available online). None of the main conclusions was impacted by FDR correction.

## Discussion

Our aim was to elucidate the role of ELS on adolescent internalizing problems and adiposity, as well as their comorbidity, based on prospective data from two population birth cohorts. We highlight two key findings. Firstly, exposure to cumulative stress is strongly associated with internalizing symptoms (especially postnatal ELS) and, to a lesser extent, with adiposity (especially prenatal ELS). Secondly, both pre- and postnatal stress associate with psycho-cardiometabolic comorbidity more strongly than to individual health outcomes.

Our first objective was to disentangle the relative contribution of prenatal and postnatal stress exposure to adolescent internalizing symptoms and adiposity.

We found that, although both pre- and postnatal ELS contribute to internalizing symptoms, the impact of postnatal stress is larger and it is not explained by prenatal confounding, while ~60% of the prenatal effect was mediated though postnatal stress. This finding aligns with previous studies investigating the contribution of prenatal and postnatal exposure to specific stressors [@Plant2015; @Clayborne2021], and holds promising clinical implications given that several aspects of the postnatal environment may be modifiable [@Yap2016]. In particular, parental risk factors (such as psychopathology), direct victimization (e.g., maltreatment) and life events emerged as independent predictors of internalizing symptoms in our exploratory analyses, indicating that these may represent important targets for intervention.

To our knowledge, no study to date has explored such timing effects on adiposity or related outcomes. Here, we found that ~70% of the effect of prenatal stress on adiposity was "direct" (i.e., not mediated by postnatal stress); the effect of postnatal stress, both as mediator and as predictor in the adjusted models, was smaller and resulted statistically significant only in GenR. While it is important to note that the effect sizes observed in the adiposity models were markedly smaller than for internalizing symptoms, these findings provide some indication that fat accumulation processes could be particularly vulnerable to (stress-induced) alterations of the prenatal environment. This is in line with previous theoretical [@Barker1998; @Gluckman2008] and empirical [@Entringer2012; @Entringer2013] accounts showcasing the impact of stress and stress hormones during prenatal life on the programming of metabolic function and obesity risk. In our exploratory follow-up analyses, we additionally found some evidence that adiposity may be more strongly associated with prenatal stress in girls, versus postnatal stress in boys. However previous accounts of these sex differences are mixed [@Paternain2013; @Murphy2017], and differences in pubertal development may be an important confounding factor that was not accounted for in our analysis.

It is also possible that stronger associations between postnatal ELS and adiposity will emerge later in development. Indeed, accumulating postnatal risks may influence biological (e.g., inflammatory and neuro-endocrine) and behavioral factors (e.g., diet and exercise) that in turn increase physical health burden, but this might become evident only later in life [@Danese2014; @Elsenburg2017].

Our second aim was to examine whether ELS relates to psycho-cardiometabolic comorbidity, as suggested by some theoretical accounts [@Juster2016], but never explicitly investigated before. If comorbidity was a discrete stress-related pathophysiological process, then the effect of ELS on comorbidity would differ from the effect of ELS on mental and physical health separately. This expectation was partially confirmed by our data: ELS increased the risk of developing comorbidity compared to being healthy and this estimate was highest relative to all other groups. However, the overlap between CIs of the comorbidity and the internalizing-only estimate indicates that neither pre- nor postnatal stress levels were sufficient to predict whether a child will develop comorbidity vs. internalizing problems alone. Notably, cross-sectional correlations between internalizing and adiposity at age 13 were small (and so were the comorbidity group sizes), which may partly explain these findings. However, comorbidity is known to increase with age [@Barnett2012] and it is possible that pre- / postnatal stress may serve as better discriminators between comorbidity and internalizing problems in older samples, with higher comorbidity rates.

This study has several important strengths. We analysed data from two large population-based cohorts with remarkably consistent results, which adds confidence to the robustness and generalizability of our findings. We used a longitudinal and comprehensive assessment of ELS, enabling us to quantify the relative contribution of pre- and postnatal exposure to a broad spectrum of stressors. We focused on two pre-clinical health markers which manifest in adolescence and may be important targets for early prevention. Also, the challenge of incomplete data and possible selection bias was thoroughly addressed by multiple imputation and sensitivity analyses. However, it is important to note that our measures of ELS and internalizing symptoms rely primarily on parent reports, which might have introduced information bias. Further, although several important confounders were taken into account, it will be important in the future to examine the role of other potential contributors, including (epi-)genetic influences [@Inoue2022], pubertal status, disability/functional impairment and other behavioral factors (e.g., sleep, exercise, diet).

In conclusion, current approaches to the prevention and management of depression and obesity have yielded limited success. We believe the adoption of an integrated, developmental framework is necessary to improve our understanding and set the stage for better detection and prevention of these disorders, both in isolation and in their comorbid form. We provide evidence that both pre- and postnatal ELS associate with adolescent internalizing symptoms (with prenatal < postnatal stress), adiposity (with prenatal > postnatal stress), and their comorbidity at age 13. While recommendations for how to best intervene when a higher psychosocial stress burden is identified are still at embryonic stage, one novel suggestion emerging from our findings is that prenatal stress may be an underrecognized factor for identifying children at higher risk of overweight. We would therefore advice clinicians to enquire about prenatal stress exposure as part of routine pediatric assessments, so that adequate monitoring and lifestyle preventative measures can be introduced as early as infancy.

Finally, as we follow these children, it will be informative to see how these associations evolve over time. For instance, the association between ELS exposure and adiposity-related outcomes may not emerge fully until adulthood and it is possible that the nature of the relation between ELS and comorbidity also differs as a function of developmental stage.

## References {.unnumbered}
::: {.sectionrefs}
:::